### PR TITLE
Commit and Userstory PDF's added

### PR DESCRIPTION
**Pull request by LiamRotchford5671**

### CODE REVIEW

**Comment by alangomez24** [comment]
I’d like a commit for the first week please

**Comment by LiamRotchford5671** [comment]
> I’d like a commit for the first week please

We counted the commits on master for each person not by branch that's why its a 0 for the first week.

**Comment by alangomez24** [comment]
Ok, so just to clarify, commits to the master unreviewed and therefore canceled (as mine was) don’t count then?

**Comment by LiamRotchford5671** [comment]
> Ok, so just to clarify, commits to the master unreviewed and therefore canceled (as mine was) don’t count then?

If you go to master branch and click on the commits button it lists all commits made it it since we began the project. That's what was counted by each week for each member.

**Comment by alangomez24** [comment]
Got it ok

**Review by SimonBartonPSU — APPROVED** [review]
Good. Merge.

**Pull request merged**
