### PR TITLE
spaceship restore

### PR DESCRIPTION
**Pull request by alangomez24**

### CODE REVIEW

**Comment by SimonBartonPSU** [comment]
Load / save appears to be working with the default game settings, but there are some issues with using the dev menu and this load/save functionality. Additionally, there is more data that needs to be saved to fully complete #2 .

Ideally all data would be saved including [sensor](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/6fc9883a03545955c4bb31e25e577fed11d75362/gameObjects.js#L39), even though upgraded sensors aren't implemented yet, having this data saving and loading now, would make things easier later.

All the data is important, but especially not saving [wormholeRandom and maxCoords](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/6fc9883a03545955c4bb31e25e577fed11d75362/gameObjects.js#L42-L44) really messes up trying to use the dev menu for customized games. As this code currently stands, I can set up a map size of 1000,1000 and location of 900,900 with the dev menu then if I save and load that game state then move, I'm instantly put in a wormhole because maxCoords aren't being saved. So that's the spaceship data. I think if everything gets saved the dev menu and load/save behavior will be less buggy.

There's also the [map](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/6fc9883a03545955c4bb31e25e577fed11d75362/gameObjects.js#L168) which gets populated in the function right below, row by row with [celestial points](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/6fc9883a03545955c4bb31e25e577fed11d75362/gameObjects.js#L174). Each celestialPoint has its own [celstialObjects array](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/6fc9883a03545955c4bb31e25e577fed11d75362/gameObjects.js#L207). 

The map needs to be saved as well, because although our planets and asteroids are [hardcoded](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/6fc9883a03545955c4bb31e25e577fed11d75362/gameObjects.js#L184-L196) now, we are going to be implementing the ability for celestial objects to be placed via the dev menu, so we need a general map saving capability.

Ha has [provided](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/6fc9883a03545955c4bb31e25e577fed11d75362/gameObjects.js#L163-L164) a couple function names that could be defined as the map save and load functions.

This is on the right track, and I'm encouraged that the default game state save/load is working. Getting the rest of the data saved is the next step. Once that's done we can do more tests.

Btw, in addition to Ha's hardcoded asteroids, the Collison List.txt file is the place to find locations to test damaged as well as other objects that just end the game.

Also, we're all learning about creating great commits, and I am certainly far from perfect, but I would recommend reading through [this](https://chris.beams.io/posts/git-commit/) guide. I figured I'd mention this, because creating strong commit messages was our actionable item from the sprint review.

**Comment by alangomez24** [comment]
Thank you for taking the time to review.

**Comment by alangomez24** [comment]
Ok Simon, I will go through your points one by one. But, please understand that this is an incremental improvement, and not a complete, final component, as is obvious from our far from complete program.

**Comment by alangomez24** [comment]
Can this pull request please be seen as an incremental improvement?

**Comment by alangomez24** [comment]
I will go through your points, thanks.

**Comment by alangomez24** [comment]
for (var i = 0; i <= spaceship.maxCoordX; i++) {
    var CPRow = [];
    for (var j = 0; j <= spaceship.maxCoordY; j++) {
      CPRow.push(new celestialPoint([i, j]));
    }
    gameSpace.push(CPRow);
  }

Can you please explain this to me?

**Comment by alangomez24** [comment]
Why do I not run into "planet celeron" at location (2,0) when it is hard coded as such

**Comment by alangomez24** [comment]
The coordinate system doesn't appear to work

**Comment by alangomez24** [comment]
I just mention it since we got into stuff that I didn't attempt to save in this pull request

**Comment by alangomez24** [comment]
if you can explain to me what on this green earth this map is I will save it

**Comment by alangomez24** [comment]
this map does not work as intended

**Comment by alangomez24** [comment]
I don't want to be blamed for errors that are not my own

**Comment by alangomez24** [comment]
my code doesn't touch your maxCoords so how could it possibly be causing that problem

**Comment by alangomez24** [comment]
When the map works, I will save it, for now please accept this because it saves spaceship variables as intended and does not do anything else except expose errors.

**Comment by alangomez24** [comment]
why do you get hit by an asteroid at (3,3)

**Comment by halyngoc** [comment]
> if you can explain to me what on this green earth this map is I will save it

The celestialMap is a set of celestialPoints. I left [these 2 methods](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/b0d9807958864d78a00745c7e358793c3096859c/gameObjects.js#L163-L164) empty. You can implement them to export the map to string and vice versa.

**Comment by alangomez24** [comment]
Ok Ha, thanks. I'm just trying to figure out how this map works.

**Pull request closed without merging**
