### PR TITLE
Gazeteer + mortality restore hotfix

### PR DESCRIPTION
**Pull request by alangomez24**
- clears and repopulates the relevant planets of the gazeteer with correct positions using planet locations as saved in map. (only other option would be to hard code the planet locations)
- saves and restores global Mortal variable

### CODE REVIEW

**Comment by SimonBartonPSU** [comment]
This works if I just modify the planets in the dev menu. But if I modify lots of things in the dev menu (map size, starting location, wormhole behavior, fixed planet locations, fixed space stations, fixed freighters, fixed meteor storms and fixed asteroids) then the gazetteer starts as empty. I suspect this problem may have to do with making the map small? I'm not exactly sure though. It seems that if the map size is left alone this problem doesn't happen. I'll try to investigate this more tomorrow.

If map size is made small (like 50,50) then Console gives me the error "Uncaught TypeError: Cannot read property '25' of undefined
    at window.onload (gameObjects.js:298)", which is referencing [this line](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/2af1f8ab475536b8748ea5ceb76a668f1308941d/gameObjects.js#L298).

If anyone has any ideas on this one, feel free to jump in.

**Comment by alangomez24** [comment]
I got the same error with property '82'

**Comment by alangomez24** [comment]
This bug can be caused by only setting the map size in the dev menu to 101, 101 with no other changes.
Smaller sizes also caused it even with adjusted starting location. If this isn't caused at all by the save menu though can we fix it in another pull request?

**Review by SimonBartonPSU — APPROVED** [review]
The map size change issue happens on master as well, so I am alright merging this with master so we can get the gazetteer fix and Mortal fix. Unless anyone objects, let's merge.

I'll be creating a separate issue for the map size bug.

**Pull request merged**
