### PR TITLE
US-2.9 Asteroid Collison

### LINKED ISSUE #32: US-2.9 Collision with an Asteroid
User Story: US-2.9
Collision with an Asteroid
Priority: 3

Story: As a player, I want to collide with an Asteroid that lies on the path between the starting point of a move and the terminating point of a move so I can add some risk to the game

### PR DESCRIPTION
**Pull request by LiamRotchford5671**
Closes #32.

Implemented asteroid Collision with the hardcoded values

Modified function directionCheck to check for asteroid collision before actual full spaceship move.

Created new function checkCollison() that implements a check on each space between start and end point for the currently hardcoded asteroid locations for a match.

If a match is made and alert box informs the player of death and reloads the game in function AsteroidCollison().

Implemented asteroid collision check for devconfig values

Implemented the chance effect 90% damage 10% death event with corresponding alerts

### CODE REVIEW

**Review by halyngoc — DISMISSED** [review]
There is a bug with energy calculation on the turn you collide with an asteroid. Basically energy depletes as if the spaceship is damaged the entire path instead of just after the collision.

Steps to reproduce:
1. Start from 0,0
2. Move up, distance of 5
3. Expected energy is `1000 - (10 + 50 * 4) = 790`. Instead what we have is `1000 - (50 * 5) = 750`

**Comment by LiamRotchford5671** [comment]
> There is a bug with energy calculation on the turn you collide with an asteroid. Basically energy depletes as if the spaceship is damaged the entire path instead of just after the collision.
> 
> Steps to reproduce:
> 
> 1. Start from 0,0
> 2. Move up, distance of 5
> 3. Expected energy is `1000 - (10 + 50 * 4) = 790`. Instead what we have is `1000 - (50 * 5) = 750`

The bug was occurring due to the spaceship.damage being set to true in the directionCheck -> AsteroidCollision function then returning back to the move : function(). In the move : function the damage calculation / energy update occurs after the movement itself so it would result in the energy be deducted as if the ship was already damaged on the first turn when the collision occurred.

Now a bool is returned and caught off directionCheck, where a simple if conditional in the move : function() after the energy calculation determines if a collision occurred and then calls the AsteroidCollision function which will apply the damage to be true. That way on the next turn damage energy consumption will be applied. With this i was also able to remove the if statements out of the switch case in directionCheck as well. 

Also small note for the arithmetic above: For a non damaged ship the calculation for a move distance of 5 would be 1000 - (10*5) = 950    and the arith for a damged ship is   1000 - (10 * 5 * 5) = 750 just so there's no confusion on review for what the end energy values should be. This was based off the energy consumption if else in the move : function()

**Comment by halyngoc** [comment]
I didn't make this clear in the review so I'll attempt to explain again. The asteroid is at 1,0. Starting from 0,0 moving up with a distance of 5, there will be 1 CP where the ship isn't damaged (energy decreases by 10) and 4 CP where it is (energy decreases by 50). You have to know where the asteroid is and make 2 separate calculations in that one turn. Afterwards you can turn on the ship is damaged flag and your current code would work.

**Comment by SimonBartonPSU** [comment]
Another example is move right 1 then up 5 then left 1, so you're at (0,5) with 930 energy. Now, if we move down 5, we'd expect the move 4 units undamaged then the final 1 unit would be with a damaged ship, so (4 * 10 + 1 * 50) = 90 energy drained, we expect to end up at 840.

The key distinction here is that the switch to damaged energy decrease happens in the same movement. So, I think collisionCheck should be called in move() and could [return](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/966d4faebbc07cd05485d5b05c2bdd8bbf4c0f70/gameObjects.js#L160) i+1 (for loop iterator) to signify where on the path an asteroid was encountered. (Same return on line 156 where Config is not null).

Then [this code](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/966d4faebbc07cd05485d5b05c2bdd8bbf4c0f70/gameObjects.js#L52-L60) could be made into a separate function (called energyDecrease()?) that would take the i+1 return value as an argument that could be used to do the separate energy decrease (just switch every 'this' to 'spaceship'). Let me know if this makes sense / you see where I'm going here or if I made things more confusing.

Also, we maybe move the retCheck stuff to just happen inside of [checkEvents](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/585e4c3e32a07c75f35691dd179ab0c64d6e7d0d/checkEvents.js#L4).

**Comment by LiamRotchford5671** [comment]
Code updated with the following meeting notes made on PR:

Moved and altered the energy depletion if else block into its own function called energyDecrease. 

CheckCollision now returns the int value along the path of the distance moved of where a collision occurred.

energyDecrease now will check first if a collision occurred based on the value returned in checkCollision if zero it will perform the normal energydecrease with the if else block that used to be in move().

If the collision value is not zero and we did collided it will deduct the value from the intdistance the ship moved along its path and decrements the amount of cp's moved non-damaged and the cp's damaged along its entire path.

Also I updated the alert message in the checkEvents.js for meteor showers so it clarifies that energy will not deplete at 5 times the normal rate.

**Comment by halyngoc** [comment]
Alright, when you resolve conflicts and I confirm it still works afterwards, I'll approve

**Comment by SimonBartonPSU** [comment]
I think [this if](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/fca565107e432fa159655757bb90b2329c5d2b2d/gameObjects.js#L116) should be if (collision === 0 || spaceship.damaged === true) , because you can start the game move up 5, which is handled correctly, but then you can move back down 5 again and the [else](https://github.com/halyngoc/CS300-Group3-SpaceHunt/blob/fca565107e432fa159655757bb90b2329c5d2b2d/gameObjects.js#L126) block is executed and the new partial damaged energy decrease happens, and I think it should just be the damaged decreased for the whole path.

**Review by SimonBartonPSU — APPROVED** [review]
Code has been tested and passed per our sprint 2 acceptance criteria. Let's merge.

**Pull request merged**
